apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: guestbook-ui
  namespace: guestspace
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: guestbook-ui
 minReplicas: 4
 maxReplicas: 8
 targetCPUUtilizationPercentage: 80
