apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: guestbook-ui
  namespace: guestspace
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: guestbook-ui
 minReplicas: 2
 maxReplicas: 8
 targetCPUUtilizationPercentage: 80
